<?php

/* PHPflow is a program which provides browser-viewable flowcharts
 * Copyright (C)2005  by Alex T.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation Europe e.V., Villa Vogelsang, Antonienallee 1,
 * 45279 Essen, Germany.
*/

// *** phpflow common functions and declarations ***

//ini_set("display_errors",true); // set only for debug purposes

// initialize config array
$PHPFLOW = array();

// version information - please do not change
$PHPFLOW["INFO"]="generated by <img src=\"phpflow_s.png\" alt=\"phpflow\"> version 0.9.2-BETA";

// include custom configuration
include_once("config.inc.php");

// logging function used if debugmode activated
function log2file($logmsg)
{
	global $PHPFLOW;
  if($PHPFLOW["DEBUGMODE"])
  { 
		if (!$fp = @fopen($PHPFLOW["DEBUGFILE"], "a")) 
		{
			echo "cannot open file (".$PHPFLOW["DEBUGFILE"].")";
			exit;
		} else {
			$status =	fwrite($fp, date("m.d.y H:i:s - ").$logmsg."\n");
			if(!$status>0)
			{
				echo "cannot write to file (".$PHPFLOW["DEBUGFILE"].")";
		  	exit;
			}
			//echo $status;
			//exit;
		}			
		if (!fclose($fp)) 
		{
			echo "cannot close file (".$PHPFLOW["DEBUGFILE"].")";
			exit;
		}
  }
}

?>