<?php

/* PHPflow is a program which provides browser-viewable flowcharts
 * Copyright (C)2005  by Alex T.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation Europe e.V., Villa Vogelsang, Antonienallee 1,
 * 45279 Essen, Germany.
*/

// *** phpflow common functions and declarations ***

//ini_set('display_errors', true); // set only for debug purposes

// initialize config array
$_PHPFLOW_config = array();

// version information - please do not change
$_PHPFLOW_config['INFO'] = 
"generated by <img src=\"phpflow_s.png\" alt=\"PHPflow\"> version 0.9.2-BETA";

// include custom configuration
include_once('config.inc.php');

// logging function used if debugmode activated
function log2file($logmsg)
{
  global $_PHPFLOW_config;
  if($_PHPFLOW_config['DEBUGMODE']) { 
    if (!$fp = @fopen($_PHPFLOW_config['DEBUGFILE'], 'a')) {
      echo 'cannot open file ('.$_PHPFLOW_config['DEBUGFILE'].')';
      exit;
    } else {
      $status =	fwrite($fp, date("m.d.y H:i:s - ").$logmsg."\n");
      if(!$status > 0) {
        echo 'cannot write to file ('.$_PHPFLOW_config['DEBUGFILE'].')';
        exit;
      }
    }			
    if (!fclose($fp)) {
      echo 'cannot close file ('.$_PHPFLOW_config['DEBUGFILE'].')';
      exit;
    }
  }
}

?>
